# Generated by Django 5.1.4 on 2025-06-03 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoadmapProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_type', models.CharField(help_text="e.g., 'backend', 'frontend' - identifies which roadmap it is", max_length=50)),
                ('progress_data', models.TextField(default='{}')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Roadmap Progress',
                'verbose_name_plural': 'User Roadmap Progresses',
                'unique_together': {('user', 'roadmap_type')},
            },
        ),
    ]
