# Generated by Django 5.1.4 on 2025-06-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRoadmapProgress',
        ),
    ]
