# Generated by Django 5.1.4 on 2025-06-03 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernodeprogress',
            name='node',
        ),
        migrations.AlterUniqueTogether(
            name='usernodeprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usernodeprogress',
            name='user',
        ),
        migrations.RenameField(
            model_name='roadmap',
            old_name='title',
            new_name='name',
        ),
        migrations.CreateModel(
            name='RoadmapProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_nodes', models.JSONField(default=dict)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='UserNodeProgress',
        ),
    ]
